### ISSUE TITLE
BUDDY closes when applying big libraries

### ISSUE THREAD

**Issue by YasinEl** [Philipbear/BUDDY_Metabolomics#1]
Hi thank you for your tool!

I have the following problem: When trying to use a bigger library (specifically: https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS_NO_PROPOGATED.msp) BUDDY just closes after I click on 'Compute selected' (not giving any error message). Smaller libraries such as https://gnps-external.ucsd.edu/gnpslibrary/BILELIB19.msp seem to work without problem. 

I am running under Microsoft Windows 10. RAM should bot be a problem since I have more than 15Gb free.

Thanks for your help,
Yasin

**Comment by Philipbear** [comment]
Hi Yasin,

Thanks for raising this issue. It turned out that it's not the problem of library size but actually some invalid database entries (see below for example, this record does not have MS/MS fragments).
![Capture](https://user-images.githubusercontent.com/50896636/185034890-e4b970b7-a6ff-4cea-98a3-860f13d6cd70.PNG)

What we will do:
1. We will fix the code shortly and publish a newer version, which at least will not crash when reading any reference libraries.
2. It is of note that MS/MS reference library records without valid formula, InChIKey, precursor m/z or MS/MS fragments will not be loaded into BUDDY and used for downstream analysis. BUDDY needs the formula information for identified metabolites to conduct the following global peak annotation. InChIKey information is needed to retrieve the descriptions from PubChem API. We will also contact the GNPS team about the MS/MS library issue. In case that you want to perform the metabolite identification, you can now use msp libraries from MS-DIAL (http://prime.psc.riken.jp/compms/msdial/main.html#MSP) or MassBank (https://mona.fiehnlab.ucdavis.edu/downloads). They can be correctly loaded into BUDDY.

I hope above information could help you.

I will re-comment on this issue whenever the newer version of BUDDY is available. It should come out in several days. Thanks again for raising the issue.

Sincerely,
Shipei

**Comment by Philipbear** [comment]
BUDDY v1.1 was just released. Please let us know if there is any other issue. Thanks!

**Comment by YasinEl** [comment]
Hello, thank you for the quick response! Unfortunately, BUDDY still crashes when loading the library. 
Also going to 'Help -> About' still gives the version as v1.0, not v1.1, despite uninstalling v1.0 and reinstalling v1.1.

In order for me to understand correctly: BUDDY needs the slots for FORMULA AND INCHIKEY filled in ALL library entries for it to load and use it?

**Comment by Philipbear** [comment]
Hi,

For an entry to be used in BUDDY, it must have both formula and InChIKey filled. The formula is used for downstream global peak annotation. The InChlKey is used to retrieve chemical information from PubChem.

In your case, the entire "ALL_GNPS_NO_PROPOGATED.msp" do not have formula information, and thus this database cannot be used in BUDDY.

We have fixed the crash issue in the ver 1.0 caused by the missing formula and InChlKey. Our new version (v1.2) only excludes those entries. In case that you use the GNPS library for annotation, you shall not run into the crash problem, but no annotations will be made due to the issue of formula unfilled.

Please feel free to give it a try and let us know if you still run into any issue.

**Comment by YasinEl** [comment]
Yes, it does not crash anymore. Thank you!

**Comment by Philipbear** [comment]
Hi Yasin,

The GNPS spectral library was just updated with formula and InChIKey information filled (https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS_NO_PROPOGATED.msp). You can now correctly load them into BUDDY for metabolite annotation.

Please feel free to give a try and let us know if there is any remaining issue.
