### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Angrist75** [Philipbear/BUDDY_Metabolomics#2]
![Error](https://user-images.githubusercontent.com/63410174/185359942-583701e5-6824-49bf-8197-b73de54cd648.png)
could you help me to find a solution?
all the best
andrea

**Comment by Philipbear** [comment]
Hi Andrea,

It's most likely that this happens due to the Windows 10 version issue. To address that, we recommend you to get the latest windows 10 update:

**select Start  > Settings  > Update & Security  > Windows Update , and then select Check for updates. If updates are available, please install them.**

After updating windows version, please try to reinstall BUDDY. Hope this helps you. Thanks.
