### ISSUE TITLE
Software closes/crashes after a few analysis.

### ISSUE THREAD

**Issue by gdiazcruz** [Philipbear/BUDDY_Metabolomics#6]
Hello developers!

Great tool! I have been using it for a few hours and I really like it. However, I've noticed that after running some analysis (nothing specific), the software closes itself with no error or explanation. I do not know if my computer is not powerful enough or if there's a different issue.

I am running .mgf files obtained from Molecular Networking (6800 features), and I have tested running one, two, five, ten and one hundred features. The last attempt with only one spectra crashed during computing. 

Also, if the software is idle for 10 minutes or so, it closes too. 

Any suggestions?

**Comment by Philipbear** [comment]
Thanks for raising this. We are currently aware of the software instability due to the large memory storage & expensive background computation tasks. Apart from the technical improvement on our side, what you can do is: 1) please do not minimize the software window when calculation, 2) please make sure that features are selected correctly before click "compute selected", there might be a lag. 3) if your PC does not have a sufficient RAM (e.g., 32GB), please do not import large data files containing >1000 features at each time.
If you ever observe any reproducible crashing issue, please let us know. Thank you so much.

**Comment by gdiazcruz** [comment]
Thanks,

I will follow your suggestions. Should anything else happen, I will communicate with you.
